name: guckelsberg
services:
  db:
    image: 'postgres:latest'
    restart: always
    env_file:
      - .env
    environment:
      - 'POSTGRES_DB=guckelsberg'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_USER=${DB_USER}'
    ports:
      - '5433:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: